### ISSUE TITLE
Extension created via contentful-cli, init is not fired and nothing is rendered on ui

### ISSUE THREAD

**Issue by vrunda-thacker** [contentful/extensions#342]
I was trying to create my own UI field extension using the steps given on Contentful documents below: https://www.contentful.com/developers/docs/extensibility/ui-extensions/managing-a-ui-extension/

For some reason my localhost:1234 server runs but nothing is loaded... The sdk's init function does not seem to fire due to which there is nothing getting added in the root div.

I also tried cloning the sample extension https://github.com/contentful/extensions/tree/master/samples/external-api This too does not load anything on localhost

Please help if anyone has successfully tried this before

**Comment by Jwhiles** [comment]
Hi @vrunda-thacker - it sounds like you are trying to access localhost:1234 directly. However Contentful apps and extensions only work when run inside of Contentful - this is because the init function is only invoked when running inside of Contentful.

Once you've run your extension, can you try logging into contentful - and assigning your extension to a ContentType - as demonstrated in [the video on this page](https://www.contentful.com/developers/docs/extensibility/ui-extensions/managing-a-ui-extension/)
